[tool.poetry]
name = "harambot"
version = "0.3.0-Beta"
description = "A Yahoo Fantasy Sports bot for Discord"
authors = ["DMcP89 <davemcpherson@wochstudios.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/DMcP89/harambot"
repository = "https://github.com/DMcP89/harambot"
keywords = [
    "yahoo", 
    "yahoo fantasy sports",
    "fantasy football",
    "fantasy basketball",
    "fantasy baseball",
    "fantasy hockey",
    "discord",
    "bot"
]

include = [
    "LICENSE.md",
]

packages = [
    {include = "harambot"},
]

[tool.poetry.dependencies]
python = "^3.8"
discord = "^2.1.0"
yahoo-fantasy-api = "^2.6.0"
dynaconf = "^3.1.11"
peewee = "^3.15.4"
cachetools = "^5.2.0"
psycopg2 = "^2.9.5"
mysqlclient = "^2.1.1"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"

[tool.poetry.scripts]
harambot = "harambot.bot:run"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
