services:
  - type: web
    name: harambot-service-blueprint
    runtime: docker
    image:
      url: docker.io/dmcp89/harambot:latest
    plan: free
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: YAHOO_KEY
        sync: false
      - key: YAHOO_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
