[default]
DISCORD_TOKEN = 'Discord API Token'
YAHOO_KEY = 'Yahoo Client ID'
YAHOO_SECRET = 'Yahoo Client Secret'
GUILD_DB = 'harambot'
GUILD_DB_USER = 'harambot'
GUILD_DB_PASS = 'harambe'
GUILD_DB_HOST = 'localhost'
GUILD_DB_PORT = 3308
DATABASE_URL = 'sqlite:///harambot.db'