[default]
LOGLEVEL = "DEBUG"
# Supported databases are sqlite, mysql, and postgres
GUILDS_DATASTORE_TYPE = "sqlite"
# if using a sqlite database specify the path to the db file
GUILDS_DATASTORE_LOC = "harambot.db"